### PR TITLE
correct eigenmethods for (very) small matrices

### PR DESCRIPTION
**Pull request by zackmdavis**
(in the matter of #46)

### CODE REVIEW

**Comment by AtheMathmo** [comment]
Thanks! Do you mind if I ask you to make a few changes? If this is a problem I am happy to make the tweaks myself :)

- Can we `match`, or at least `if { ..} else if {... } else { ... }`.
- Can we pull out the bulk of each method into new private methods. i.e. `fn fisher_shift_eigenvalues` and `fn fisher_shift_eigendecomp`. That one is on me - sorry...
- Can we add a test for 2x2 eigenvectors. I wont hold the lack of other tests against you - once again that is on me!

Thanks again for putting this PR together - it is greatly appreciated!

**Comment by zackmdavis** [comment]
OK (give me a few days; busy week; didn't finish the eigenvectors test).

**Comment by AtheMathmo** [comment]
No problem at all. This isn't blocking any other work so you can take as long as you need.

**Comment by zackmdavis** [comment]
b5df97a

**Comment by AtheMathmo** [comment]
This is awesome, thank you!

**Pull request merged**
