### PR TITLE
0.5.0 version release

### PR DESCRIPTION
**Pull request by AtheMathmo**
Making a PR for this as I've made quite a few changes to the markdown docs.

This includes changes from @theotherphil , @NivenT , and @andrewcsmith . If each of you could take a look and make sure I haven't missed anything I'd appreciate it!

If anyone has the patience to check the copy changes that would be great too!

### CODE REVIEW

**Comment by andrewcsmith** [comment]
Looks good to me. Thanks.

**Comment by theotherphil** [comment]
Looks good.

**Comment by NivenT** [comment]
What they said.

**Comment by AtheMathmo** [comment]
Ah I forgot @tafia . Did I miss anything from the rulinalg version bump?

**Comment by tafia** [comment]
Looks good to me as well. Good job everyone, it is impressive

**Comment by AtheMathmo** [comment]
Awesome! I'll merge this soon

**Pull request merged**
