### PR TITLE
Add setters and a specified constructor: kmeans

### PR DESCRIPTION
**Pull request by danlrobertson**
Add a constructor with specified values for all options for the KMeansClassifier. In addition, add setters for each field. Not super attached to any of the components of the patch besides `KMeansClassifier::new_specified`. I also added some rules to `.gitignore` for the sanity of vim users :smile:

---
This change is [Reviewable](https://reviewable.io/reviews/athemathmo/rusty-machine/30)

### CODE REVIEW

**Comment by AtheMathmo** [comment]
Thanks for helping out! K-Means was one of the first algorithms I implemented and so was some of the first rust code I wrote - it definitely needs some work.

As of right now all of the struct fields are public and so setter's aren't _needed_. However, I agree with your logic that we probably shouldn't allow fields to be set on models which have been trained. I think we should make the struct fields private and introduce these setters. This is a breaking change though and so I may hold off on merging it for a little while.

Also I totally agree there should be a constructor that doesn't just use the default initialization algorithm. I'm not a huge fan of the name you picked but I can't think of anything better :D.

_Irrelevant to PR: Would be great to see some of this macro magic on issue #29 if yo're up for it? It's a much bigger task though and also should probably be tackled after #22. No pressure!_

**Comment by danlrobertson** [comment]
> I think we should make the struct fields private and introduce these setters. This is a breaking change though and so I may hold off on merging it for a little while.
>
> Also I totally agree there should be a constructor that doesn't just use the default initialization algorithm. 

I agree. My current thoughts... So perhaps this should be broken up into 2 PRs. One to add another constructor (sorry for the C++isms :smile:) and one large PR probably maintained on a separate branch to be merged at some later date with a major or minor version bump (depending on how you're going to handle releases and versioning) that uses getters and setters for algorithm fields (ensuring a common interface across all algorithm structures).

> I'm not a huge fan of the name you picked but I can't think of anything better :D.

I am absolutely horrendous at naming things :smile:

> Irrelevant to PR: Would be great to see some of this macro magic on issue #29 if yo're up for it? It's a much bigger task though and also should probably be tackled after #22. No pressure!

I'd be happy to take a look. I've got a few other PRs && isssues that I've got to do some work on, but I'll take a look and post my findings/thoughts on the issue sometime this week

**Comment by AtheMathmo** [comment]
I think you're suggestion is a good one. I'll merge the changes you propose in this PR and include them as part of the next patch release. We'll include the larger changes in a separate PR.

Currently my plan is to allow (minor) breaking changes in minor (0.X.0) releases. For example making the k-means fields private but providing setters. Patches (0.0.X) releases should be completely back compatible (though I have been adding functionality in these versions too).

I'll spend a couple days mulling over the name (I'm also terrible at naming things, as you can probably tell). It will likely remain as you suggested though.

Thanks again!

**Comment by zackmdavis** [comment]
On the question of argument signature for initializers where some parameters should have a default, the [builder pattern](https://doc.rust-lang.org/book/method-syntax.html#builder-pattern) might be a good fit?

``` rust
struct KMeansClassifierBuilder {
    k: usize,
    iters: usize,
    init_algorithm: InitAlgorithm
}

impl KMeansClassifierBuilder {
    fn new(k: usize) -> Self {
        KMeansClassifierBuilder {
            k: k,
            iters: 100,
            init_algorithm: InitAlgorithm::KPlusPlus
        }
    }

    fn iters(&mut self, iters: iters) -> &mut KMeansClassifierBuilder {
        self.iters = iters;
        self
    }

    // ... &c.

    fn finalize(&self) -> KMeansClassifier {
        KMeansClassifier {
            k: k,
            iters: 100,
            centroids: None,
            init_algorithm: InitAlgorithm::KPlusPlus
        }
    }
}
```

**Comment by AtheMathmo** [comment]
Thanks for checking out the PR Zack!

I'm at a bit of a crossroads with this one. I really like the builder syntax in rust but there are a couple issues with implementing it here (I think):

- We don't use it anywhere else in the library. I'm trying to focus on homogeneity within the library and this goes against that.
- This is a very **rust**y thing to do. I _think_ most of the users of this library will be either new to Rust or new to machine learning and I don't want to isolate one group or the other.

The first issue could be solved by using this syntax throughout the library. The second I'm not sure can be solved?

These are just my thoughts though. I'm happy to be overruled by popular opinion and make this change in a future larger update.

**Comment by AtheMathmo** [comment]
@danlrobertson @zackmdavis - Do either of you have any more thoughts on this PR? 

I'm still pretty conflicted but I think if there are no objections I'll merge the PR as is - it adds some needed functionality without breaking anything. We'll definitely need to address the issues discussed initially but can create a new issue for that.

I do like the builder pattern - especially in this case. But I'm not sure how it affects the balance I discussed in the previous comment.

**Comment by danlrobertson** [comment]
I definitely think the Builder pattern is the way to go, but I agree that it may cause less experienced users some hardships. My thoughts...

 - Add a constructor that allows setting everything (mostly done)
 - Make the current members private
 - Add `setters` and `getters` (mostly done)
 - @zackmdavis submits a PR with his example code using the builder pattern and highly publicize this as the way to go in any documentation and tutorials, but hang on to the current API to allow for easy use by newer users.

Just my thoughts... I'm happy to do some work on this PR if there is consensus on the above or other items.

**Comment by AtheMathmo** [comment]
Ok, I think we should go with the builder syntax. However if we do this I think to keep a clean API we should not have setters on the KMeansClassifier struct (this is just my thinking, if this goes against convention let me know!).

I would modify your suggestion to the following:

- Keep the current _default_ constructor which lets us choose only the number of clusters. I think this should be available to keep things easy as you say - and additionally the settings aren't critically important for K-Means.
- Make the current members private. (Perhaps keep them public for this initial PR, and have a new PR to make them private as a breaking change).
- Add `getters`.
- Add the builder to this PR. Include example usage in module documentation, and for the struct documentation.

This to me seems like a good compromise - we don't break things (yet). We provide the right way to build a k-means classifier. We keep things rust-like without adding a necessary learning curve.

How does this sound to each of you? I'm happy again to be overruled.

**Comment by zackmdavis** [comment]
_(shrugging)_ My intuition kind of expects `::new` to take the complete complement of possible arguments, but I understand that that would have the non-ergonomic consequence of the I-don't-care-just-give-me-the-defaults initializer call being `KMeansClassifierBuilder::new(k).finalize()`, which we likely want to avoid ...

**Comment by AtheMathmo** [comment]
You make a good point. It seems that due to my current shoddy design that whatever has some negative consequence.

I think we should still have a simple default constructor for the `KMeansClassifier` but I'm not too concerned about how this looks exactly. In the world of idiomatic Rust would you expect to have a fully specified `new` function if there is a builder present as well? We could always change the `new` function to `from_cluster_count` or something less verbose?

**Comment by danlrobertson** [comment]
@zackmdavis: I made a commit using your code and committed using you as the author. Let me know if you have any issues with that. If you would rather submit a separate PR or a PR against my branch. I'm totally okay with that. I just thought this was probably the easiest option.

Still not perfect, but I think we're getting there. After writing out the examples I'm really starting to see the benefit of going the route of using a builder pattern.

**Comment by zackmdavis** [comment]
> using you as the author. Let me know if you have any issues with that.

I appreciate the gesture, but I think the commit authorship should be in your name; my comment with the trivial code snippet was just a comment (which might or might not be worth citing in the commit message, but IMO isn't worth forging the author field for).

**Comment by AtheMathmo** [comment]
I agree that this is looking a lot better - the builder pattern does indeed seem like the way to go. I'm still unsure about including the `new_specified` method in addition to the builder - it is redundant and I feel that we will want to remove it in the future. That said - it isn't bad to include it at this point.

Another minor point - my understanding is that in Rust it is standard to exclude the `get_` part on your get methods, so the methods in this PR would become:

```rust
/// Get the number of classes
pub fn k(&self) -> usize {
    self.k
}
 
/// Get the number of iterations
 pub fn iters(&self) -> usize {
    self.iters
}
 
/// Get the initialization algorithm
pub fn init_algorithm(&self) -> InitAlgorithm {
    self.init_algorithm
}
```

**Comment by danlrobertson** [comment]
Awesome! I'm also conflicted about the name, but I can't think of anything better...

I squashed the two commits and removed the `get_` from the getters.

**Comment by AtheMathmo** [comment]
My argument for `new_specified` was more that we can now achieve this functionality using the builder and so no longer need this function at all. However it may keep things easy if we include it for now :).

I just checked out the branch and there a couple provlems. It looks like there is a typo, on line 100:

```rust
fn iters(&mut self, iters: iters) ...
```

has `iters` as the type. It should read:

```rust
fn iters(&mut self, iters: usize) ...
```

Additionally the builder methods need to be public or they cannot be accessed (the current doc tests fail). We also do not need to return the `&mut` reference (although the builder example @zackmdavis gave does). I'd suggest the function should be, e.g:

```rust
pub fn iters(&mut self, iters: usize) {
    self.iters = iters;
}
```

Are you happy making these changes?

**Comment by AtheMathmo** [comment]
The functionality here is looking great now - thanks for your hard work!

There is only one more thing I have just thought of - which I am happy to exclude (you've already put up with a lot of my comments!). I think we should add some documentation explaining what the purpose of the builder is. I'm thinking that the `KMeansClassifierBuilder` struct documentation should explain what it does? I think the usage is described well enough in the examples (though it may be worth adding some inline comments to make it clear that we get a `KMeansClassifier` out. e.g.

/// ```
/// use rusty_machine::learning::k_means::KMeansClassifierBuilder;
///
/// // Create a new classifier with 5 clusters.
/// let model : KMeansClassifier = KMeansClassifierBuilder::new(5).finalize();
/// ```

As I say though - not necessary. Give me the go ahead and I'll merge. Thanks again!

**Comment by danlrobertson** [comment]
Thanks for the comments. They were super helpful! Sorry it took so many revisions :smile:

**Comment by AtheMathmo** [comment]
Glad it was helpful :). And I think it took so many revisions as we were figuring what we needed as we went along - thanks for your help delivering a great addition!

**Pull request merged**
